language: python

python:
  - "3.5"

env:
  - TOX_ENV=py27-flake8
  - TOX_ENV=py35-django110
  - TOX_ENV=py34-django110
  - TOX_ENV=py27-django110
  - TOX_ENV=py35-django19
  - TOX_ENV=py34-django19
  - TOX_ENV=py27-django19
  - TOX_ENV=py35-django18
  - TOX_ENV=py34-django18
  - TOX_ENV=py27-django18

install:
  - pip install tox
  - pip install -r requirements.txt
  - pip install coveralls

script:
  - tox -e $TOX_ENV

after_script:
  coveralls
